<?php

namespace SfWebApp\MainBundle\Repository;

/**
 * CibleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CibleRepository extends \Doctrine\ORM\EntityRepository
{
}
