<?php

namespace SfWebApp\MainBundle\Repository;

/**
 * Sous_secteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sous_secteurRepository extends \Doctrine\ORM\EntityRepository
{
}
